---
- name: Bootstrap and Deploy Application
  hosts: web
  become: true
  gather_facts: false # Absolute must

  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_pkg_mgr: yum # Hardcode this globally
    app_dir: /home/ec2-user/app
    docker_image: myapp
    container_name: myapp
    app_port: 80

  tasks:
    - name: Install Python 3 requirements (Raw)
      raw: |
        sudo yum install -y python3 python3-pip python3-libselinux
      changed_when: true

    - name: Set Python symlink
      raw: sudo ln -sf /usr/bin/python3 /usr/bin/python
      changed_when: true

    - name: Deploy Application Role
      include_role:
        name: app-role
