---
- name: Add ec2-user to docker group (Raw)
  raw: sudo usermod -aG docker ec2-user
  changed_when: true

- name: Create app directory (Raw)
  raw: mkdir -p {{ app_dir }} && sudo chown ec2-user:ec2-user {{ app_dir }}
  changed_when: true

- name: Copy application code
  # If this specific task fails, we will move to a 'git clone' approach
  copy:
    src: ../app/
    dest: "{{ app_dir }}/"
    owner: ec2-user
    group: ec2-user

- name: Build Docker image (Raw)
  raw: cd {{ app_dir }} && sudo docker build -t {{ docker_image }} .
  changed_when: true

- name: Stop existing container (Raw)
  raw: sudo docker rm -f {{ container_name }} || true
  changed_when: true

- name: Run Docker container (Raw)
  raw: sudo docker run -d -p {{ app_port }}:3000 --name {{ container_name }} {{ docker_image }}
  changed_when: true