---
- name: Install required packages
  yum:
    name:
      - docker
      - git
      - python3-pip
    state: present

- name: Start Docker
  service:
    name: docker
    state: started
    enabled: true

- name: Add ec2-user to docker group
  user:
    name: ec2-user
    groups: docker
    append: yes

- name: Create app directory
  file:
    path: /home/ec2-user/app
    state: directory

- name: Copy application code
  copy:
    src: /home/ec2-user/terraform_anisble/app/
    dest: /home/ec2-user/app/

- name: Build Docker image
  shell: |
    cd /home/ec2-user/app
    docker build -t myapp .

- name: Stop existing container (if any)
  shell: |
    docker rm -f myapp || true

- name: Run Docker container
  shell: |
    docker run -d -p 80:3000 --name myapp myapp
